### ISSUE TITLE
Agent fails to read Rust symbols

### ISSUE THREAD

**Issue by purkhusid** [parca-dev/parca-agent#475] opened 2022-06-18 08:49 UTC
I was looking into using Parca to profile a Rust binary but it fails to read the symbols from the binary.
I have verified that the binary does include the symbols.

The error I receive in the agent is:
```
level=warn ts=2022-06-18T00:55:37.856812691Z caller=maps.go:106 msg="failed to read object build ID" object=/proc/21830/root/app/src/rust/graphql/src/api/bin.runfiles/monorepo/src/rust/graphql/src/api/bin err="get elf build id: note name too long (5590599 bytes)"
```

Compilation OS: Fedora 35
Agent deployed on k8s cluster running Debian hosts
Rust version: 1.61.0

**Comment by kakkoyun** [comment] 2022-06-20 07:06
@purkhusid Thanks a lot for reporting. We might have broken the compatibility. I'll check it.

If it helps your onboarding, we have an example for Rust https://github.com/parca-dev/parca-demo/blob/main/rust

**Comment by purkhusid** [comment] 2022-06-20 09:47
@kakkoyun My binary is compiled using the same flags as in the example. The only difference is that it's edition 2021 instead of 2018.

**Comment by purkhusid** [comment] 2022-06-20 09:57
I tried rolling the agent back to v0.0.7 but it has the same issue

**Comment by kakkoyun** [comment] 2022-06-20 10:06
Ok, thanks a lot for trying it out with the older version. I'll make sure we fix this issue before releasing the next version (which we were planning to do today).

**Comment by purkhusid** [comment] 2022-06-21 11:10
@kakkoyun I think I figured out  why this is not working for me. I'm building the binary using Bazel and rules_rust(https://github.com/bazelbuild/rules_rust). My guess is that the build ID is not added to the binary because it's not a reproducible action.

If I run `debug-inf buildid binary` then I only get:
```
level=info msg=done!
```
I'm not too familiar with the significance of the build ID and if it makes sense to let Parca accept binaries with no build IDs, what do you think?

**Comment by brancz** [comment] 2022-06-21 11:16
This strikes me as odd, build-ids can be deterministic, the build tool can decide it, it's just opaque bytes. If the binary is reproducible, then the build-id may just as well be. It's only a problem when the binary itself is not byte-by-byte reproducible because that could mean that the debuginfos are different for each build (at which point calling it "reproducible" is arguably false).

I'm not too familiar with bazel (especially bazel+rust), could this be a bug in the rust rules for bazel?

**Comment by kakkoyun** [comment] 2022-06-21 11:17
We use build-id heavily to uniquely identify the object files in our system. It's the key for storing debug information, mapping, etc. However, we should be able to fall back on generating a hash from the `.text` section to identify these binaries distinctly. The output shows me that we failed to even that.

How easy for you to provide a dummy (like a hello world program) executable from this particular bazel pipeline?

**Comment by kakkoyun** [comment] 2022-06-21 11:53
Using the tip of the main and the given example the build-id extraction works:

```
❯ ./dist/debug-info buildid ../../Sandbox/rules_rust_build_id/bazel-bin/bin
Build ID: 983bd888c60ead8e
level=info msg=done!
```

This could be fixed on the main. However, there are other issues on the main. Currently, I'm trying to fix those. I'm planning to cut a release candidate as soon as they're fixed. I'll let you know when I have a release candidate, and maybe you will give it another shot.

**Comment by purkhusid** [comment] 2022-06-21 11:58
Awesome! I'll test it once you have a release cut.

**Closed** 2022-06-30 17:09 UTC
Labels: bug

**Comment by kakkoyun** [comment] 2022-06-30 17:11
@purkhusid The main branch of Parca Server and Agent should be stable now to test.
