### ISSUE TITLE
Ensure short-lived processes are well supported

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#1619] opened 2023-05-09 15:11 UTC
With frame pointers as well as DWARF-based unwinding, and figure out the min latency we support from the moment we see these processes to the moment we can collect the first stacktrace 

[testdata](https://github.com/parca-dev/testdata/blob/main/src/main.go) has now a go binary to help reproduce this

cc @kakkoyun

**Comment by kakkoyun** [comment] 2023-05-11 10:19
@javierhonduco duplicate of https://github.com/parca-dev/parca-agent/issues/1429? Or do they have different intentions?

**Comment by javierhonduco** [comment] 2023-05-11 10:28
I don't mind if we close one, I opened https://github.com/parca-dev/parca-agent/issues/1429 to fix the problem, generally, and this issue refers to the latest proc info changes that aimed to fix this problem but didn't seem to help as much as we expected

**Comment by kakkoyun** [comment] 2023-06-16 13:38
![CleanShot 2023-06-16 at 15 37 03](https://github.com/parca-dev/parca-agent/assets/536449/d1f71877-56b6-4676-8774-c86f47ef856c)

`watch -n1 ./out/basic-go 200`

**Comment by javierhonduco** [comment] 2023-06-16 14:17
The lower `[jit]` frame seems incorrect

**Comment by kakkoyun** [comment] 2023-06-16 14:48
> The lower `[jit]` frame seems incorrect

I'm kindly leaving further tests to you for Monday :) I don't think the behavior is different from the latest stable version.
Maybe we're just wrongly naming it as `[jit]` when we don't have a name for the mapping.

**Comment by kakkoyun** [comment] 2023-06-19 18:11
Closing this issue for now.
We can track further improvements in #1429

**Closed by kakkoyun** 2023-06-19 18:11 UTC
Labels: P0, area/process-discovery
