### ISSUE TITLE
panic: file is already closed

### ISSUE THREAD

**Issue by sdirkwinkel** [parca-dev/parca-agent#1798] opened 2023-06-27 12:14 UTC
**Describe the bug**
parca-agent crashes after a couple seconds/minutes

**To Reproduce**

**Logs**
```
panic: file is already closed
file /tmp/1de6a59761eabfc258289226f63e7b6b256ce11b107442076 is already closed by: github.com/parca-dev/parca-agent/pkg/objectfile.callers (github.com/parca-dev/parca-agent/pkg/objectfile/object_file.go:143) /github.com/parca-dev/parca-agent/pkg/objectfile.(*ObjectFile).close (github.com/parca-dev/parca-agent/pkg/objectfile/object_file.go:127) /github.com/parca-dev/parca-agent/pkg/objectfile.(*Pool).onEvicted (github.com/parca-dev/parca-agent/pkg/objectfile/pool.go:156) /github.com/parca-dev/parca-agent/pkg/cache.NewLRUCacheWithEvictionTTL[...].func1 (github.com/parca-dev/parca-agent/pkg/cache/cache_with_ttl.go:145) /github.com/parca-dev/parca-agent/pkg/cache/lru.(*LRU[...]).removeElement (github.com/parca-dev/parca-agent/pkg/cache/lru/lru.go:118) /github.com/parca-dev/parca-agent/pkg/cache/lru.(*LRU[...]).removeOldest (github.com/parca-dev/parca-agent/pkg/cache/lru/lru.go:108) /github.com/parca-dev/parca-agent/pkg/cache/lru.(*LRU[...]).Add (github.com/parca-dev/parca-agent/pkg/cache/lru/lru.go:70) /github.com/parca-dev/parca-agent/pkg/cache.(*LRUCacheWithEvictionTTL[...]).Add (github.com/parca-dev/parca-agent/pkg/cache/cache_with_ttl.go:158) /github.com/parca-dev/parca-agent/pkg/objectfile.(*Pool).NewFile (github.com/parca-dev/parca-agent/pkg/objectfile/pool.go:301) /github.com/parca-dev/parca-agent/pkg/objectfile.(*Pool).Open (github.com/parca-dev/parca-agent/pkg/objectfile/pool.go:204) /github.com/parca-dev/parca-agent/pkg/process.(*MapManager).newUserMapping (github.com/parca-dev/parca-agent/pkg/process/maps.go:206) /github.com/parca-dev/parca-agent/pkg/process.(*MapManager).MappingsForPID (github.com/parca-dev/parca-agent/pkg/process/maps.go:136) /github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).fetch (github.com/parca-dev/parca-agent/pkg/process/info.go:255) /github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).Info (github.com/parca-dev/parca-agent/pkg/process/info.go:295) /github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).Run (github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:602) /main.run.func15.1 (github.com/parca-dev/parca-agent/cmd/parca-agent/main.go:889) /runtime/pprof.Do (runtime/pprof/runtime.go:44) /main.run.func15 (github.com/parca-dev/parca-agent/cmd/parca-agent/main.go:888) /github.com/oklog/run.(*Group).Run.func1 (github.com/oklog/run@v1.1.0/group.go:38) /runtime.goexit (runtime/asm_amd64.s:1598) /

runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
golang.org/x/sync/singleflight.newPanicError({0x1f0ba00?, 0xc0012b2b40})
        golang.org/x/sync@v0.3.0/singleflight/singleflight.go:35 +0x2c
golang.org/x/sync/singleflight.(*Group).doCall.func2.1()
        golang.org/x/sync@v0.3.0/singleflight/singleflight.go:184 +0x3b
panic({0x1f0ba00, 0xc0012b2b40})
        runtime/panic.go:884 +0x213
github.com/parca-dev/parca-agent/pkg/objectfile.(*ObjectFile).Reader(0xc000a74090)
        github.com/parca-dev/parca-agent/pkg/objectfile/object_file.go:71 +0x405
github.com/parca-dev/parca-agent/pkg/debuginfo.(*Manager).upload(0xc00071bce0, {0x251fe98?, 0xc0013b94a0?}, 0xc000a74090)
        github.com/parca-dev/parca-agent/pkg/debuginfo/manager.go:441 +0x273
github.com/parca-dev/parca-agent/pkg/debuginfo.(*Manager).Upload.func3()
        github.com/parca-dev/parca-agent/pkg/debuginfo/manager.go:392 +0x29
golang.org/x/sync/singleflight.(*Group).doCall.func2(0xc0024f7786, 0xc00129a280, 0x7f180c6013c8?)
        golang.org/x/sync@v0.3.0/singleflight/singleflight.go:189 +0x6f
golang.org/x/sync/singleflight.(*Group).doCall(0x1ed43e0?, 0xc00133a720?, {0xc000c66120?, 0x28?}, 0x0?)
        golang.org/x/sync@v0.3.0/singleflight/singleflight.go:191 +0xa5
golang.org/x/sync/singleflight.(*Group).Do(0xc00043d740, {0xc000c66120, 0x28}, 0x1?)
        golang.org/x/sync@v0.3.0/singleflight/singleflight.go:104 +0x165
github.com/parca-dev/parca-agent/pkg/debuginfo.(*Manager).Upload(0xc00071bce0, {0x251fe98, 0xc0013b8390}, 0xc000a74090)
        github.com/parca-dev/parca-agent/pkg/debuginfo/manager.go:391 +0x445
github.com/parca-dev/parca-agent/pkg/debuginfo.(*Manager).UploadMapping(0xc00071bce0, {0x251fe98?, 0xc001172480?}, 0xc000a8ab40)
        github.com/parca-dev/parca-agent/pkg/debuginfo/manager.go:195 +0x6f6
github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).uploadMapping(0xc00071bd90, {0x251fe98, 0xc0009b8030}, 0xc000a8ab40)
        github.com/parca-dev/parca-agent/pkg/process/info.go:423 +0x369
github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).Run.func1()
        github.com/parca-dev/parca-agent/pkg/process/info.go:382 +0xec
created by github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).Run
        github.com/parca-dev/parca-agent/pkg/process/info.go:371 +0x115


goroutine 206 [running]:
golang.org/x/sync/singleflight.(*Group).doCall.func1()
        golang.org/x/sync@v0.3.0/singleflight/singleflight.go:161 +0x2d3
golang.org/x/sync/singleflight.(*Group).doCall(0x1ed43e0?, 0xc00133a720?, {0xc000c66120?, 0x28?}, 0x0?)
        golang.org/x/sync@v0.3.0/singleflight/singleflight.go:196 +0xc2
golang.org/x/sync/singleflight.(*Group).Do(0xc00043d740, {0xc000c66120, 0x28}, 0x1?)
        golang.org/x/sync@v0.3.0/singleflight/singleflight.go:104 +0x165
github.com/parca-dev/parca-agent/pkg/debuginfo.(*Manager).Upload(0xc00071bce0, {0x251fe98, 0xc0013b8390}, 0xc000a74090)
        github.com/parca-dev/parca-agent/pkg/debuginfo/manager.go:391 +0x445
github.com/parca-dev/parca-agent/pkg/debuginfo.(*Manager).UploadMapping(0xc00071bce0, {0x251fe98?, 0xc001172480?}, 0xc000a8ab40)
        github.com/parca-dev/parca-agent/pkg/debuginfo/manager.go:195 +0x6f6
github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).uploadMapping(0xc00071bd90, {0x251fe98, 0xc0009b8030}, 0xc000a8ab40)
        github.com/parca-dev/parca-agent/pkg/process/info.go:423 +0x369
github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).Run.func1()
        github.com/parca-dev/parca-agent/pkg/process/info.go:382 +0xec
created by github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).Run
        github.com/parca-dev/parca-agent/pkg/process/info.go:371 +0x115

```

**Software (please complete the following information):**
 - parca-agent, version  (commit: d43328fc3b9f2ea0875a32d5d67146720aabc3ff, date: 2023-06-26T02:18:12Z), arch: amd64
 - 0.20 has the same behavior
 

**Environment (please complete the following information):**
- Linux Distribution: debian 11
- Linux Version: 6.2.5
- Arch: amd64

**Comment by brancz** [comment] 2023-06-27 12:18
Thank you so much for reporting! Could you describe the nature of the workload that is running on these hosts? Also do you run this in a Kubernetes environment or just on plain Linux?

**Comment by sdirkwinkel** [comment] 2023-06-27 12:32
Just plain linux, some docker containers and qemu / libvirt VMs. The host do mainly CI, so lots of container / vm starts.

I'll try to get an easier reproducer

**Comment by brancz** [comment] 2023-06-27 12:57
Could you try setting the `--object-file-pool-size` to something significantly higher than the default like 2048 and see if the problem persists? Once high enough it should fix the cause of closing the file prematurely.

I'll think about how we can handle this a bit more gracefully.

**Comment by javierhonduco** [comment] 2023-07-06 10:53
Saw this while running the integration tests off `37cbc2362d1a674d96`:

```
panic: file is already closed
file /proc/271641/root/usr/lib64/libc.so.6 is already closed (try increasing `--object-file-pool-size`) it was closed by: github.com/parca-dev/parca-agent/pkg/objectfile.callers (/home/javierhonduco/code/parca-agent/pkg/objectfile/object_file.go:143) /github.com/parca-dev/parca-agent/pkg/objectfile.(*ObjectFile).close (/home/javierhonduco/code/parca-agent/pkg/objectfile/object_file.go:127) /github.com/parca-dev/parca-agent/pkg/objectfile.(*Pool).onEvicted (/home/javierhonduco/code/parca-agent/pkg/objectfile/pool.go:156) /github.com/parca-dev/parca-agent/pkg/cache.NewLRUCacheWithEvictionTTL[...].func1 (/home/javierhonduco/code/parca-agent/pkg/cache/cache_with_ttl.go:145) /github.com/parca-dev/parca-agent/pkg/cache/lru.(*LRU[...]).removeElement (/home/javierhonduco/code/parca-agent/pkg/cache/lru/lru.go:118) /github.com/parca-dev/parca-agent/pkg/cache/lru.(*LRU[...]).Remove (/home/javierhonduco/code/parca-agent/pkg/cache/lru/lru.go:100) /github.com/parca-dev/parca-agent/pkg/cache.(*LRUCacheWithEvictionTTL[...]).Get (/home/javierhonduco/code/parca-agent/pkg/cache/cache_with_ttl.go:174) /github.com/parca-dev/parca-agent/pkg/objectfile.(*Pool).get (/home/javierhonduco/code/parca-agent/pkg/objectfile/pool.go:162) /github.com/parca-dev/parca-agent/pkg/objectfile.(*Pool).Open (/home/javierhonduco/code/parca-agent/pkg/objectfile/pool.go:194) /github.com/parca-dev/parca-agent/pkg/process.(*MapManager).newUserMapping (/home/javierhonduco/code/parca-agent/pkg/process/maps.go:216) /github.com/parca-dev/parca-agent/pkg/process.(*MapManager).MappingsForPID (/home/javierhonduco/code/parca-agent/pkg/process/maps.go:136) /github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).fetch (/home/javierhonduco/code/parca-agent/pkg/process/info.go:255) /github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).Fetch (/home/javierhonduco/code/parca-agent/pkg/process/info.go:209) /github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).prefetchProcessInfo (/home/javierhonduco/code/parca-agent/pkg/profiler/cpu/cpu.go:315) /github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).listenEvents.func2 (/home/javierhonduco/code/parca-agent/pkg/profiler/cpu/cpu.go:342) /runtime.goexit (/usr/local/go/src/runtime/asm_amd64.s:1598) /

```

**Comment by v-thakkar** [comment] 2023-07-06 11:53
I've been seeing the same kind of errors while running integration tests locally. They go away after doing `make clean` after every few iterations.

**Comment by javierhonduco** [comment] 2023-07-06 14:42
Mmm it's probably not consistent because there is a race, surprised that running `make clean` fixes things, but perhaps I am missing something!

**Comment by javierhonduco** [comment] 2023-09-27 07:53
This panic was removed in the PR mentioned above. Some error messages might be shown regarding this same condition, but it won't panic anymore. Deferring the decision of closing it to @kakkoyun

**Comment by kakkoyun** [comment] 2023-09-27 07:56
> This panic was removed in the PR mentioned above. Some error messages might be shown regarding this same condition, but it won't panic anymore. Deferring the decision of closing it to @kakkoyun

Yep, closing it.

**Closed** 2023-09-27 07:56 UTC
