### ISSUE TITLE
Missing label target label

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#254] opened 2022-02-23 11:00 UTC
I have a deployment.yaml as should below, and I'm not able to find the profiles on Parca UI with app="demo-nextjs" query.
<img width="438" alt="Screenshot_2022-02-22_at_4 44 28_PM" src="https://user-images.githubusercontent.com/536449/155306548-36fee3c5-6334-4913-9406-64e4a22482fc.png">
<img width="1578" alt="Screenshot_2022-02-23_at_10 40 37_AM" src="https://user-images.githubusercontent.com/536449/155306553-fe463ee6-f35c-47d0-8e5c-b62b24a0a0c4.png">

cc @Sylfrena

**Comment by brancz** [comment] 2022-02-25 10:49
It just dawned on me, this is one of those features that we wanted to enable using relabeling. This actually turns out to be a feature that we haven't implemented/finished yet, not a bug.

**Comment by Sylfrena** [comment] 2022-12-01 17:27
Fixed in #887

**Closed by Sylfrena** 2022-12-01 17:27 UTC
Labels: enhancement
